name: wakatime-stats

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{6a1a415d-be6b-4c13-a728-caa00820082e}}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LANGUAGE: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_COMMIT: "False"
